### ISSUE TITLE
Unable to add a new repo.

### ISSUE THREAD

**Issue by donmccurdy** [openleap/openleap.github.com#2]
Hi, is the openleap org still active and accepting repos? I'm working on something that I'd consider transferring (an [A-Frame / Leap Motion component](https://github.com/donmccurdy/aframe-leap-hands)), but GitHub doesn't let me transfer the repo or create new repos without admin rights:

> You don’t appear to have permission to create repositories for this organization. Sorry about that.

I'm also unable to edit existing repos, so I'm not sure how I'd continue contributing if this were moved over.

**Comment by Cervator** [comment]
Hey @donmccurdy !

I'm still here, @owenversteeg might be too, activity just fell off a cliff after some of the initial hype about the Leap died off. There's still plenty of potential and I'd love to get back to playing with the device, just haven't had the time. I wish the company would do some more to sponsor some open source work or so :-)

What likely happened on repo transferring is that GitHub changed org permission roles and the "general admin" role changed, now everything except owner is per repo.

I don't know if it'll still work the old way if I add you to a legacy team without migrating it, but lets give it a try! Adding you to the transferrers team. See if it'll work now?

If not I'm happy to just create a new repo, add a new team with admin access to it, and add you to it as a team maintainer. Then you can just push your existing repo's content to the new repo as if it was new content, but it'll retain history etc. Wouldn't keep the 4 issues but those I figure can be recreated.

**Comment by donmccurdy** [comment]
That worked, thanks! 

My interest died off for a while as well but I'm giving it another try with the Orion release and A-Frame VR. We'll see what happens, I guess. :)

**Comment by Cervator** [comment]
Yeah I was blown away by the Orion + VR combo. Really neat! 

I'm still shopping some Leap and VR options around between interested contributors over in Terasology land, and at least one GSOC student did a proposal on the Leap. We just had to narrow the field way down, alas :-)

Anytime you need something administrative within this org just let me know!

**Comment by Cervator** [comment]
Bumped you back up to admin on your repo again as well :-)

**Comment by owenversteeg** [comment]
Hey!

Yup - there was an initial spike of a huge amount of activity and now it's down to pretty low levels. People are still around though for sure, and I think the use of the Leap for VR will bring back a lot of people into Leap development.

@Cervator Thanks for that! I assume all the permissions are good now? Lemme know if you (or anyone else) wants any permissions for anything, I'm also getting used to the new GH permissions settings.

@donmccurdy Looks cool, thanks! Best of luck with your project!

**Comment by Irtechie** [comment]
I had kept up the original .net DLL’s for 4.5/6 

These still needed?

**Comment by Cervator** [comment]
Hey @owenversteeg yep all set for now I think :-)

Hi @Irtechie and huh? :D
